# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bs-dna-methyl',
                'doc_host': 'https://magistak.github.io',
                'git_url': 'https://github.com/magistak/bs-dna-methyl',
                'lib_path': 'bs_dna_methyl'},
  'syms': {'bs_dna_methyl.core': {'bs_dna_methyl.core.foo': ('core.html#foo', 'bs_dna_methyl/core.py')}}}
