"""Download processed RRBS data. This is usually in BED format."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_download_processed.ipynb.

# %% auto 0
__all__ = ['use_get_projects']

# %% ../nbs/00_download_processed.ipynb 5
from geofetch import Geofetcher

# %% ../nbs/00_download_processed.ipynb 7
import time, random
def use_get_projects(self, acc, max_attempts=10):
    "Added randomly timed retries to `Geofetcher.get_projects`, so it works."
    try:
        return self.get_projects(acc)
    except Exception as e:
        if max_attempts <=1:
            raise
        delay = max(0.1, random.normalvariate(1, 0.5))
        time.sleep(delay)
        return self.use_get_projects(acc, max_attempts - 1)
    
Geofetcher.use_get_projects = use_get_projects
