"""Download processed RRBS data. This is usually in BED format."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_download_processed.ipynb.

# %% auto 0
__all__ = ['memory', 'Geofetcher']

# %% ../nbs/00_download_processed.ipynb 4
from geofetch import Geofetcher as OriginalGeofetcher
from tenacity import retry, wait_exponential, stop_after_attempt 
from joblib import Memory

memory = Memory(".cache", verbose=0)

# %% ../nbs/00_download_processed.ipynb 5
@memory.cache
@retry(
    wait=wait_exponential(multiplier=0.5, min=0.1, max=10),
    stop=stop_after_attempt(10),
    reraise=True
)
def _get_projects_cached(*args, **kwargs):
    fetcher = OriginalGeofetcher()
    return fetcher.get_projects(*args, **kwargs)

# %% ../nbs/00_download_processed.ipynb 6
class Geofetcher(OriginalGeofetcher):
    "Patched and extended version of Geofetcher class from `geofetcher`."
    def get_projects(self, *args, **kwargs):
        return _get_projects_cached(*args, **kwargs)

